services:
  postgres:
    image: postgres:17
    container_name: ticket-service-db
    environment:
      POSTGRES_DB: ticketdb
      POSTGRES_USER: ticket_user
      POSTGRES_PASSWORD: ticket_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ticket_user -d ticketdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ticket-service-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ticketdb
      SPRING_DATASOURCE_USERNAME: ticket_user
      SPRING_DATASOURCE_PASSWORD: ticket_pass
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata: